name: movie_hub
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  dio: ^5.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1
  intl: ^0.18.1
  go_router: ^7.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

